### ISSUE TITLE
Check setuptools min version

### ISSUE THREAD

**Issue by frascuchon** [recognai/biome-text#131]
Some insttallations raises setuptools error related to `find_namespaced_packages` method:

```bash
Obtaining file:///Users/lea/Documents/biome-text
    ERROR: Command errored out with exit status 1:
     command: /Users/lea/.biome/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/lea/Documents/biome-text/setup.py'"'"'; __file__='"'"'/Users/leirea/Documents/biome-text/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fg/mftly61x1dvbs5dp3p6v5_vh0000gp/T/pip-pip-egg-info-sd6_7k75
         cwd: /Users/leirea/Documents/biome-text/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/lea/Documents/biome-text/setup.py", line 6, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name 'find_namespace_packages'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
make: *** [dev] Error 1
```

installation should find installed setuptools version and check if compatible

**Comment by dcfidalgo** [comment]
fixed by #134
