### ISSUE TITLE
How AllenNLP deals with empty Fields.

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#61]
This issue just describes how AllenNLP deals with empty Fields, that is Fields (`TextField`, `LabelField`) created with empty strings. How we currently deal with empty strings is described in #59 .

An empty string in the `LabelField` results in an empty string class when creating the vocab for the labels.

An empty `TextField` passed on directly to the model results in an error:
```
    Traceback (most recent call last):
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/david/recognai/biome/biome-text/src/biome/allennlp/__main__.py", line 78, in <module>
    main()
  File "/Users/david/recognai/biome/biome-text/src/biome/allennlp/__main__.py", line 71, in main
    args.func(args)
  File "/Users/david/recognai/biome/biome-text/src/biome/allennlp/commands/learn/learn.py", line 128, in learn_from_args
    workers=args.workers,
  File "/Users/david/recognai/biome/biome-text/src/biome/allennlp/commands/learn/learn.py", line 195, in learn
    force=True,
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/commands/train.py", line 252, in train_model
    metrics = trainer.train()
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
    output_dict = self.model(**batch)
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/david/recognai/biome/biome-text/src/biome/allennlp/models/sequence_classifier.py", line 41, in forward
    encoded_text = self.forward_tokens(tokens)
  File "/Users/david/recognai/biome/biome-text/src/biome/allennlp/models/base_model_classifier.py", line 164, in forward_tokens
    tokens, mask=mask, num_wrapping_dims=self._num_wrapping_dims
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 131, in forward
    token_vectors = embedder(*tensors, **forward_params_values)
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/modules/token_embedders/token_characters_encoder.py", line 35, in forward
    return self._dropout(self._encoder(self._embedding(token_characters), mask))
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/modules/time_distributed.py", line 34, in forward
    reshaped_inputs = [self._reshape_tensor(input_tensor) for input_tensor in inputs]
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/modules/time_distributed.py", line 34, in <listcomp>
    reshaped_inputs = [self._reshape_tensor(input_tensor) for input_tensor in inputs]
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/modules/time_distributed.py", line 67, in _reshape_tensor
    raise RuntimeError(f"No dimension to distribute: {input_size}")
RuntimeError: No dimension to distribute: torch.Size([1, 0])
```

A completely empty `ListField([])` results in the following error:

```
  File "/Users/david/anaconda3/envs/biome/lib/python3.6/site-packages/allennlp/data/fields/list_field.py", line 30, in __init__
    str(field_class_set)
AssertionError: ('ListFields must contain a single field type, found set()', 'occurred at index 0')
```

Empty `TextField`s get padded in a `ListField`. For example, if there is a `ListField` with 3 `TextField`s (the first not empty, the last two empty) the mask looks like 
```
[[[1, ...], [0], [0]]]
```
Also, if you specify sorting by "num_fields" in the trainer, `ListField`s with different lengths get padded. For example, if you have 2 `ListField`s with 3 and 2 `TextField`s, the mask for the second `TextField` looks like 
```
[[[1, ...], [1, ...], [0]]]
```

**Comment by dcfidalgo** [comment]
Comment by @frascuchon :
> 
> @dcfidalgo Refering you commented:
> 
> ```comment
> Also, if you specify sorting by "num_fields" in the trainer, ListFields with different lengths get padded. For example, if you have 2 ListFields with 3 and 2 TextFields, the mask for the second TextField looks like
> ```
> 
> 
> I think we can handle by sorting by `num_tokens` too:
> 
> sorting_keys:
> ```yaml
> - ["record1", "num_fields"]
> - ["record1", "list_num_tokens"]
> ```
> 
> See [here](https://github.com/allenai/allennlp/issues/3049#issuecomment-509780889)
